import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {SafeContentArea} from "@/components/safe-content-area";
import {I18nProvider} from "@/i18n/provider";
import {getLocale} from "@/i18n/locale";

import "./globals.css";

import {AppRoot} from '@telegram-apps/telegram-ui';
import '@telegram-apps/telegram-ui/dist/styles.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();

    return (
        <html lang={locale}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <I18nProvider>
            <AppRoot>
                <SafeContentArea>
                    {children}
                </SafeContentArea>
            </AppRoot>
        </I18nProvider>
        </body>
        </html>
    );
}
